### ISSUE TITLE
Problem setting options for UglyMol 6.0.4

### ISSUE THREAD

**Issue by John-Holt-Tessella** [uglymol/uglymol#10]
I am having troubles calling:
```
Viewer({viewer: 'viewer',  hud: 'hud',    help: 'help'})
```
It seems to fail in the iterable statement https://github.com/uglymol/uglymol/blob/master/src/viewer.js#L449 because the option object above is not iterable. It is also different code to what is at   https://github.com/uglymol/uglymol/blob/master/uglymol.js#L6776 which does not iterate aoround the options adding them to config. 

At the moment I have created a work around adding to the options passed to viewer and iterable but I don't think this is the right solution:

```
    defaultViewerOptions[Symbol.iterator] = function () {
        let n=-1;
        let keys = Object.keys(this);
        return {
            next() {
            n+=1;
            done = (n === keys.length);
            return {value:keys[n], done:done}
            }
        }
```

I am a bit rusty at Javascript so please let me know is this does not make sense

**Comment by wojdyr** [comment]
I haven't been using JS myself for a couple years, so I didn't remember it. But yes, checking the docs, Object is not iterable. So apparently it has never been working as intended.

The code in viewer.js and uglymol.js differs, because it was transpiled with [Buble](https://github.com/bublejs/buble). All the configuration is in the repo.

I'll try to fix it (not today, but at some point).
